### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Helldemon2017** [ntm-development/issues#1]
**Command/Bug**
music is laggy

**Time**
When did this bug occur?
*Do not specify "Just Now", "Today at 4:43pm", "10/20/2019" etc. as the time!*

**Server (with ID)**
natebot rewrite beta server

**Screenshots/Discord Message Links and/or Recorded Footage**
This is very important, not providing any evidence to this bug will be ignored.
*Use Imgur Image links, Discord Message Links (Right click on message and copy it) and Upload Screen recorded evidence to YouTube*

**Describe the bug**

**Additional Comments**

**Comment by BookishWaffle** [comment]
Hey, there. I believe this isn’t an issue with NateBot, it’s more than likely the connection between NateBot’s core server and the server region your discord server is on. Please consider flushing through each region and tell me if whatever one works.

**Comment by NTMNathan** [comment]
This has been fixed in the new Nate Bot Stage 1 Update. Thanks for Reporting.
