### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Helldemon2017** [ntm-development/issues#2]
**Command/Bug**
spotify

**Time**
When did this bug occur?
*Do not specify "Just Now", "Today at 4:43pm", "10/20/2019" etc. as the time!*

**Server (with ID)**
Panda Testing Server

**Screenshots/Discord Message Links and/or Recorded Footage**
http://prntscr.com/rr03qy

**Describe the bug**
doesnt give what im listening too

**Additional Comments**

**Comment by NTMNathan** [comment]
Just tried to reproduce the bug, could not seem to reproduce it. So I am closing and putting a "Won't Fix/Add" Label. Thanks for reporting.
